/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicAuthRouteImport } from './routes/_public-auth'
import { Route as PublicAuthIndexRouteImport } from './routes/_public-auth.index'
import { Route as PublicAuthLoginRouteImport } from './routes/_public-auth.login'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_public-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthIndexRoute = PublicAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicAuthIndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof PublicAuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/login': typeof PublicAuthLoginRoute
  '/': typeof PublicAuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public-auth': typeof PublicAuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/_public-auth/login': typeof PublicAuthLoginRoute
  '/_public-auth/': typeof PublicAuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/api/auth/$' | '/api/public/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/login' | '/' | '/api/auth/$' | '/api/public/$'
  id:
    | '__root__'
    | '/_public-auth'
    | '/dashboard'
    | '/_public-auth/login'
    | '/_public-auth/'
    | '/api/auth/$'
    | '/api/public/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-auth': {
      id: '/_public-auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-auth/': {
      id: '/_public-auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthIndexRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public-auth/login': {
      id: '/_public-auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthIndexRoute: typeof PublicAuthIndexRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthIndexRoute: PublicAuthIndexRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
